name: Run Grid Bot

on:
#Schedule:
#    - cron: '*/5 * * * *'  # Runs every 5 minutes (if using scheduled triggers)
  workflow_dispatch:      # Enables manual trigger button in GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          STELLAR_SECRET_KEY: ${{ secrets.STELLAR_SECRET_KEY }}
        run: grid_bot.py
